"""rename department

Revision ID: 27105c962639
Revises: 0e41e5007ff1
Create Date: 2025-11-14 18:26:22.754727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27105c962639'
down_revision = '0e41e5007ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
